config/routes.rb
AMPTA::Application.routes.draw do

resources :projects do
resources :tickets
end

resources :tickets
resources :projects
resources :users

  root :to => 'sessions#login'

  match "home", :to => "sessions#home"
    match "register", :to => "users#new"
   match "login", :to => "sessions#login"
    match "logout", :to => "sessions#logout"

  match "tickets", :to => "tickets#tickets"

  match ':controller(/:action(/:id))(.:format)'
end

app/models/project.rb
class Project < ActiveRecord::Base


  has_and_belongs_to_many :users
  has_many :tickets, :dependent => :destroy

  attr_accessible  :name, :description, :start_date, :end_date, :user_ids

   validates :name,
   :presence => {:message => "You need to specify a name"},
    :length => {:minimum => 6, :maximum => 50, :message => "A project has to have atleast 6 characters, max 50"}

     validates :description,
   :presence => {:message => "You need to specify a description"},
    :length => {:minimum => 6, :maximum => 50, :message => "A description has to have atleast 6 characters, max 50"}

      validate :end_date_cannot_be_less_then_start_date

private



def self.search(search)
  if search
    find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
  else
    find(:all)
  end
end



def end_date_cannot_be_less_then_start_date
errors.add(:end_date, "can't be less than the start date") if
      !end_date.blank? and end_date < start_date
end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController


def index
    @projects = Project.search(params[:search])
    @tickets = Ticket.all
    @projects_sorted = @projects.sort_by(&:updated_at).reverse
    @project_id= session[:user_id]
  end

  def show
    @project = Project.find(params[:id])
    @users = User.all
    @session = User.find(session[:user_id])
    @user_id= session[:user_id]
    @included = @project.users.include? (@session)
  end

  def destroy
    @project = Project.find(params[:id])
    @project_id= session[:user_id]

    if(@project.user_id == @project_id)
      Project.destroy(params[:id])
      redirect_to projects_path
      flash[:notice] = "Project deleted!"

    else
      redirect_to :action => 'show', :id => @project.id
    end
  end

 def edit
    @session_id = User.find(session[:user_id]).id
    @project = Project.find(params[:id])
    @users = User.all
    @session_id = session[:user_id]
    @users = User.where("id != ?", @session_id)
    if(@project.user_id == @session_id)
      @project = Project.find(params[:id])

    else
      redirect_to :action => 'show', :id => @project.id
    end
  end

  def update
    @session_id = User.find(session[:user_id]).id
    @project = Project.find(params[:id])
     @users = User.where("id != ?", @session_id)
    if(@project.user_id == @session_id)
      if @project.update_attributes(params[:project])
        redirect_to :action => 'show', :id => @project.id
        flash[:notice] = "Project updated!"
      else
        render 'edit'
      end
    end
  end

  def new
    @project = Project.new
    @users = User.all
    @session_id = session[:user_id]
    @users = User.where("id != ?", @session_id)
end

  def create
    @project = Project.new(params[:project])
    @project.user_id = session[:user_id]
    @session_id = session[:user_id]
    @users = User.where("id != ?", @session_id)

    if @project.save
      redirect_to projects_path
      flash[:notice] = "Project created!"
    else
      render :action => "new"
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
  <div id="project"><h1> Edit project: <%= @project.name %></h1>

  <% if @project.errors.any? %>
<div class="alert alert-error">
  <h2><%= pluralize(@project.errors.count, "error") %> in the form. Please correct.

    <ul>
      <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>

  </div>
  <% end %>


  <%= form_for(@project) do |f| %>

<div class="text_field">
<%=f.label :name %>
<%=f.text_field :name %>
</div>

<div class="text_field">
<%=f.label :description %>
<%=f.text_area :description %>
</div>


<%=f.label 'Users Assigned' %>
<% @users.each do |u| %>
      <%= check_box_tag :user_ids, u.id, @project.users.include?(u), :name => 'project[user_ids][]' -%>

        <%= label_tag :users_ids, u.username.capitalize %>

<% end %>


<div class="text_field">
<%=f.label :start_date %>
<%=f.datetime_select :start_date %>
</div>


<div class="text_field">
<%=f.label :end_date %>
<%=f.datetime_select :end_date %>
</div>


<%= f.submit "Spara" %>


<% end %>
</div>

app/views/projects/index.html.erb
<div id="project">


<%= render 'layouts/search' %>

<br />
<h1>Projects: </h1>
<% if @projects.blank? %>
<p>No projects.</p>
<% end %>

<% else %>
<% @projects_sorted.each do |project| %>

<div class="single_proj">
  <br />
<%  if project.user_id == @project_id %>

<h4>Owner of:</h4>
<% end %><h2><%= link_to project.name, project_path(project) %></h2>
<br />
<br />




<% end %>

</div>

</div>

app/views/projects/new.html.erb
<div id="project">
<h1> Create a new project </h1>
<% if @project.errors.any? %>
<div class="alert alert-error">
  <h2><%= pluralize(@project.errors.count, "error") %> in the form. Please correct.

    <ul>
      <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>

  </div>
  <% end %>

<%= form_for(:project, :url => {:controller => 'projects', :action => 'create'}) do |f| %>
  <div class="text_field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
    <br />

  <%= f.label :description %><br />
    <%= f.text_area :description %>
    <br />


  <%=f.label 'Users Assigned' %>
    <% @users.each do |u| %>
      <%= check_box_tag :user_ids, u.id, @project.users.include?(u), :name => 'project[user_ids][]' -%>

        <%= label_tag :users_ids, u.username.capitalize %>

<% end %>

    <br />


    <%= f.label :start_date %><br />
    <%= f.datetime_select :start_date %>
    <br />

    <%= f.label :end_date %><br />
    <%= f.datetime_select :end_date %>
    <br />
  </div>
    <div class="submit">
    <%= f.submit "Skapa" %>
  </div>


  <% end %></div>

app/views/projects/show.html.erb
<div id="project"><h1><%= @project.name %></h1>

<p><strong>Description: </strong> <%= @project.description %><br />
<strong>Start Date :</strong> <%= @project.start_date %><br />
<strong>End Date:</strong> <%= @project.end_date%><br />
</p>

<strong>Users Assigned:</strong>
<br />
<%  if @project.user_id == @session %>
You(Owner)
<br />
<% end %>
<% @project.users.each do |u| %>
<%= u.username %>

<br />
<% end %>
<br />
        <br />
<div class="ticketlist">
<h4> Tickets for <%= @project.name %>: </h4>
<% @project.tickets.each do |t| %>

<%= link_to t.name, ticket_path(t) %> -   Type: <%= t.status.status_name %><br />
<br />
<% end %>

<br /> <br />

<% if @included || @project.user_id == @user_id%>

<%= link_to "New ticket", new_project_ticket_path(@project) %><br />
<% end %>
</div>
<br /><br />
<%  if @project.user_id == @user_id %>
<b> <%= link_to 'Edit', {:action => 'edit', :id => @project.id} %></b><br />
<b> <%= link_to "Delete",  project_path(@project),
:method => :delete,
:confirm => "Are you sure you want to delete this project?" %></b>
<% end %>
<br /><br /><br />
<%= link_to 'Back', {:controller => 'projects'} %>
</div>