config/routes.rb
AMPTA::Application.routes.draw do

resources :projects do
resources :tickets
end

resources :tickets
resources :projects
resources :users

  root :to => 'sessions#login'

  match "home", :to => "sessions#home"
    match "register", :to => "users#new"
   match "login", :to => "sessions#login"
    match "logout", :to => "sessions#logout"

  match "tickets", :to => "tickets#tickets"

  match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">

    <div class="container">
      <%= link_to "CU Project Handler", '#', id: "logo" %>

      <nav>
        <ul class="nav pull-right">
<%unless session[:user_id]%>

<li><%= link_to :Register , :register, class: "nav_links"%></li>
<li><%= link_to :Login , :login, class: "nav_links"%></li>
</ul>

<%else%>
<ul class="nav">
<li><%= link_to :Home , :projects, class: "nav_links" %> </li>
<li><%= link_to 'New Project' ,  :controller => 'projects', :action => :new %> </li>
<li><%= link_to :Logout , :logout, class: "nav_links", :confirm => "Are you sure you want to log out?" %></li>
<% @username = User.find(session[:user_id]).username %>
<li><b>Logged in as:  <%= @username  %></b></li>
</ul>
<%end%>
</div>

        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_search.html.erb
<%= form_tag projects_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project Management</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">

      <div class="span11">
        <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>
      <%= yield %>
    </div>
</div>

</body>
</html>